/**
 * Proprietary — Copyright (c) 2024–2026 Kim Gurinov (Gurver).
 * Author: Kim Gurinov <kurinov@gurver.org> <kim@gurver.com>
 * Website: https://gurver.com
 * Fingerprint: GURVER-KG-AITIM-2026-7F3C9E2A
 * License: Proprietary. All rights reserved. See LICENSE / COPYRIGHT.
 *
 * Curated product changelog. Newest entries first is optional — the feed
 * helpers sort by publishedAt. Prefer appending new objects at the top for
 * human readability when editing.
 *
 * When you ship a user-visible change (any AI or human), add an entry here.
 * See docs/whats-new.md.
 */

import type { WhatsNewFeed } from "./types";

export const whatsNewFeed: WhatsNewFeed = {
  schemaVersion: 1,
  entries: [
    {
      id: "2026-08-08-word-paste-images-persist",
      date: "2026-08-08",
      publishedAt: "2026-08-08T12:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Word images stay in Docs after pasting",
      body: "Pasting from Word now places text immediately, shows steady image placeholders with upload progress, and saves each permanent image as soon as it is ready. Images no longer flicker, disappear when uploads finish, or get lost when collaboration connects.",
      href: "/docs",
      tags: ["docs", "images", "paste", "reliability"],
    },
    {
      id: "2026-08-08-super-agent-memory-search-ui",
      date: "2026-08-08",
      publishedAt: "2026-08-08T20:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Search past Super Agent chats & manage memory",
      body: "Agents can pull short snippets from earlier conversations when you ask what you discussed before. On Edit Agent → Memory, add, edit, or delete preferences, facts, and when→do flows.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory"],
    },
    {
      id: "2026-08-08-super-agent-memory-layers",
      date: "2026-08-08",
      publishedAt: "2026-08-08T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Smarter Super Agent memory (less chat bloat)",
      body: "Agents keep small curated preferences, facts, and when→do flows on the prompt — not full chat logs. Longer threads use a rolling summary plus the last few messages to save tokens.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory"],
    },
    {
      id: "2026-08-08-super-agent-disable-delete",
      date: "2026-08-08",
      publishedAt: "2026-08-08T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Turn Super Agents off or delete them",
      body: "From Super Agents hub or agent settings, turn an agent off so it leaves Chat, or permanently delete ones you own (Super Admins can remove system agents too).",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-ops-guide",
      date: "2026-08-07",
      publishedAt: "2026-08-08T00:10:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Smarter Super Agents — Docs formatting & safety",
      body: "Agents now know how the Hub works, write Docs with proper headings and lists (Markdown → TipTap), refuse accidental page wipes, and can tell you what they can vs can’t do from chat.",
      href: "/chat",
      tags: ["chat", "super-agents", "docs", "safety"],
    },
    {
      id: "2026-08-07-super-agent-create-groups",
      date: "2026-08-07",
      publishedAt: "2026-08-07T23:55:00.000Z",
      kind: "new",
      module: "shell",
      title: "Control who can create Super Agents",
      body: "Super Admins can open Settings → Super Agents and allow selected Entra groups to create agents. Super Admins can always create; everyone else follows this toggle.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "settings", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-people",
      date: "2026-08-07",
      publishedAt: "2026-08-07T23:30:00.000Z",
      kind: "new",
      module: "shell",
      title: "Share Super Agents with admins and users",
      body: "Add people to a Super Agent as Members (chat) or Admins (edit). Optionally limit chat to the roster only — like ClickUp sharing.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "sharing", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-owner-writes",
      date: "2026-08-07",
      publishedAt: "2026-08-07T22:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Owners can update docs and memory in Super Agent chat",
      body: "If you created a Super Agent (or you're a Super Admin), you can ask it to append knowledge to linked Docs and to remember preferences — right from the conversation.",
      href: "/chat",
      tags: ["chat", "super-agents", "docs", "memory"],
    },
    {
      id: "2026-08-07-super-agent-memory-ui",
      date: "2026-08-07",
      publishedAt: "2026-08-07T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Super Agents remember — and edit like ClickUp",
      body: "Agent setup now uses Instructions, Triggers, Skills, Knowledge, and Memory tabs. Tagged Docs become knowledge automatically, and agents can keep recent context, preferences, and learned facts so they improve over time.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory", "knowledge"],
    },
    {
      id: "2026-08-07-super-agent-builder",
      date: "2026-08-07",
      publishedAt: "2026-08-07T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Build your own Super Agents",
      body: "Admins can create Super Agents from a natural-language brief, edit instructions, tools, Docs knowledge, and models — then chat with them like ClickUp. Use a stronger model to draft the agent and a cheaper one for everyday replies.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "builder", "docs"],
    },
    {
      id: "2026-08-06-chat-super-agents",
      date: "2026-08-06",
      publishedAt: "2026-08-06T22:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Chat with Super Agents",
      body: "Open Chat from the sidebar and talk to Super Agents like Deadline Dale — private threads that can surface your overdue tasks as clickable chips, ClickUp-style.",
      href: "/chat",
      tags: ["chat", "super-agents", "ai"],
    },
    {
      id: "2026-08-06-assignee-label-left",
      date: "2026-08-06",
      publishedAt: "2026-08-06T16:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "People and tags are easier to scan",
      body: "The Assignees and Tags labels now sit to the left of their pickers in task creation and task details, making task fields more compact and consistent.",
      href: "/tasks",
      tags: ["tasks", "assignees", "tags", "layout"],
    },
    {
      id: "2026-08-06-custom-field-label-layouts",
      date: "2026-08-06",
      publishedAt: "2026-08-06T15:30:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Custom fields explain themselves",
      body: "Custom fields can now include optional help text and place their label above, below, beside, inside, or out of sight. The chosen presentation follows the field into task creation and task details.",
      href: "/tasks",
      tags: ["custom-fields", "task-layout", "accessibility"],
    },
    {
      id: "2026-08-06-super-admin-hidden-permissions",
      date: "2026-08-06",
      publishedAt: "2026-08-06T15:00:00.000Z",
      kind: "fixed",
      module: "admin",
      title: "One clear Admin role in permissions",
      body: "The permissions matrix now shows only the configurable space Admin role. Super Admin remains an unrestricted platform safeguard managed outside the matrix and cannot be accidentally edited or duplicated.",
      tags: ["permissions", "roles", "admin"],
    },
    {
      id: "2026-08-06-aacc-actions-menu-system",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Action menus now share one AACC design",
      body: "Settings, option menus, and right-click actions across the Operations Hub now use consistent spacing, typography, teal focus states, branded borders, and clearer destructive actions.",
      tags: ["design", "navigation", "accessibility"],
    },
    {
      id: "2026-08-06-aacc-task-actions-menu",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Task actions get a modern AACC design",
      body: "Task option menus now use a clearer branded header, fast icon actions, organized sections, and distinct lifecycle controls. The same design appears from task tables, boards, detail pages, and right-click menus.",
      href: "/tasks",
      tags: ["tasks", "design", "navigation"],
    },
    {
      id: "2026-08-06-doc-panels-collapsed",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "A cleaner, faster Pages rail",
      body: "The Pages and Styles panels now start collapsed, while the Pages rail remains available from the first page. Hover over any page to add a subpage, duplicate its full page tree, or copy and move it between Docs from the options menu.",
      href: "/docs",
      tags: ["docs", "navigation", "editor"],
    },
    {
      id: "2026-08-06-theme-bootstrap-react-19",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Theme loading is clean in modern browsers",
      body: "The light and dark theme bootstrap no longer produces a React script warning during client rendering while still preventing a flash of the wrong theme.",
      tags: ["theme", "reliability"],
    },
    {
      id: "2026-08-06-new-doc-first-save",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:30:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "New Docs save cleanly the first time",
      body: "Creating and immediately editing a Doc no longer produces a false message that somebody else saved the page. Local autosave and live collaboration now choose one save path before editing begins.",
      href: "/docs",
      tags: ["docs", "autosave", "collaboration"],
    },
    {
      id: "2026-08-06-local-login-visibility",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:00:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "Local account sign-in is available when enabled",
      body: "The login page now shows the AACC email and password form in production environments that explicitly allow local accounts. If no sign-in method is configured, the page explains what needs administrator attention instead of appearing empty.",
      href: "/login",
      tags: ["login", "reliability"],
    },
    {
      id: "2026-08-05-platform-connection-stability",
      date: "2026-08-05",
      publishedAt: "2026-08-06T03:30:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "More reliable connections across the Operations Hub",
      body: "Docs collaboration, presence updates, and database-backed screens now recover more gracefully from brief connection interruptions. Health checks also report transient database failures more reliably.",
      tags: ["reliability", "docs", "platform"],
    },
    {
      id: "2026-08-05-cewd-operations-workspace",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:55:00.000Z",
      kind: "new",
      module: "tasks",
      title: "CEWD Operations replaces the legacy demo workspace",
      body: "The old Safety sample has become a CEWD-focused workspace for discovering, validating, and delivering cross-functional workflows. It starts with a guided pilot-selection task and CEWD-specific fields.",
      href: "/tasks/cewd-operations",
      tags: ["cewd", "workflows"],
    },
    {
      id: "2026-08-05-duplicate-docs-navigation",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:45:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "One clear home for Docs",
      body: "The duplicate Docs item has been removed from navigation. The remaining Docs destination opens the shared knowledge hub.",
      href: "/docs",
      tags: ["navigation", "docs"],
    },
    {
      id: "2026-08-05-aacc-operations-hub-brand",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "AACC Operations Hub gets its college look",
      body: "The platform now uses AACC's logo and visual identity, with college teal, deep teal, and orange carried through navigation, forms, dashboards, notifications, and dark mode.",
      href: "/",
      tags: ["brand", "platform"],
    },
    {
      id: "2026-08-05-docs-all-docs-hub",
      date: "2026-08-05",
      publishedAt: "2026-08-05T22:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "All Docs hub — like ClickUp, without the sidebar tree",
      body: "Docs now opens a table of every root doc (name, location, updated, sharing). Nested pages and multi-level subpages live inside the open document outline — not under the main nav. Templates for Project Overview, Meeting Notes, and Wiki are on the hub.",
      href: "/docs",
      tags: ["docs", "hub", "wiki"],
    },
    {
      id: "2026-08-05-docs-tree-embeds",
      date: "2026-08-05",
      publishedAt: "2026-08-05T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Live task embeds in Docs",
      body: "In any page, type / and choose Task to embed a live chip with number, title, and status that opens the task.",
      href: "/docs",
      tags: ["docs", "embeds"],
    },
    {
      id: "2026-08-05-docs-module",
      date: "2026-08-05",
      publishedAt: "2026-08-05T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Docs — knowledge pages next to your work",
      body: "Create SOPs, meeting notes, and wikis from the Docs hub or directly on a task. Pages live in a space, nest as subpages, support protect + verify for freshness, and link back to tasks so knowledge stays with the work.",
      href: "/docs",
      tags: ["docs", "wiki", "knowledge"],
    },
    {
      id: "2026-08-04-whats-new-header",
      date: "2026-08-04",
      publishedAt: "2026-08-04T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: '"What\'s New" updates in the header',
      body: "A megaphone icon in the top bar now shows what changed after each update, so you always know what's new since your last visit.",
      tags: ["changelog", "onboarding"],
    },
  ],
};
