/**
 * Proprietary — Copyright (c) 2024–2026 Kim Gurinov (Gurver).
 * Author: Kim Gurinov <kurinov@gurver.org> <kim@gurver.com>
 * Website: https://gurver.com
 * Fingerprint: GURVER-KG-AITIM-2026-7F3C9E2A
 * License: Proprietary. All rights reserved. See LICENSE / COPYRIGHT.
 *
 * Curated product changelog. Newest entries first is optional — the feed
 * helpers sort by publishedAt. Prefer appending new objects at the top for
 * human readability when editing.
 *
 * When you ship a user-visible change (any AI or human), add an entry here.
 * See docs/whats-new.md.
 */

import type { WhatsNewFeed } from "./types";

export const whatsNewFeed: WhatsNewFeed = {
  schemaVersion: 1,
  entries: [
    {
      id: "2026-08-15-outreach-aacc-colors",
      date: "2026-08-15",
      publishedAt: "2026-08-15T23:00:00.000Z",
      kind: "improved",
      module: "platform",
      title: "Outreach uses AACC Hub colors",
      body: "Corporate Outreach now uses AACC teal and orange — the same palette as the rest of Hub — instead of the earlier Salesforce-blue styling.",
      href: "/outreach",
      tags: ["outreach", "brand"],
    },
    {
      id: "2026-08-15-outreach-follow-events",
      date: "2026-08-15",
      publishedAt: "2026-08-15T22:00:00.000Z",
      kind: "new",
      module: "platform",
      title: "Follow Outreach records and schedule events",
      body: "Follow a lead, opportunity, account, or quote to keep it on Outreach Home. New Event now schedules a real meeting with start and end times — it shows under Upcoming, and you can mark it complete.",
      href: "/outreach",
      tags: ["outreach", "follow", "events"],
    },
    {
      id: "2026-08-15-outreach-edit",
      date: "2026-08-15",
      publishedAt: "2026-08-15T21:00:00.000Z",
      kind: "improved",
      module: "platform",
      title: "Edit Outreach records",
      body: "Leads, opportunities, accounts, and quotes can now be edited from the record header or the Details tab. Changes save immediately and show up in the activity timeline.",
      href: "/outreach",
      tags: ["outreach", "leads", "quotes"],
    },
    {
      id: "2026-08-15-corporate-outreach",
      date: "2026-08-15",
      publishedAt: "2026-08-15T20:00:00.000Z",
      kind: "new",
      module: "platform",
      title: "Corporate Outreach pipeline",
      body: "Corporate Outreach can now work leads, opportunities, and quotes in AACC Hub — with a stage path, training products, and Hub tasks you create or connect from the record. Start from Outreach in the sidebar.",
      href: "/outreach",
      tags: ["outreach", "leads", "quotes", "tasks"],
    },
    {
      id: "2026-08-15-wcag-aa-framework",
      date: "2026-08-15",
      publishedAt: "2026-08-15T18:00:00.000Z",
      kind: "improved",
      module: "platform",
      title: "Easier keyboard and screen reader use",
      body: "AACC Hub now includes a skip-to-content path, clearer page landmarks, visible keyboard focus, and labeled time-tracking and sign-in controls so the workspace meets WCAG 2.1 AA expectations for public-college software.",
      href: "/",
      tags: ["accessibility", "keyboard", "screen-reader"],
    },
    {
      id: "2026-08-15-time-tracked",
      date: "2026-08-15",
      publishedAt: "2026-08-15T16:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Track time on tasks",
      body: "Log hours with a timer or a quick 3h 20m entry — from any task, the list Time tracked column, or the header tracker. Notes, tags, billable time, your timesheet, and a weekly dashboard are included.",
      href: "/tasks/timesheet",
      tags: ["tasks", "time", "timesheet"],
    },
    {
      id: "2026-08-14-attachment-version-history",
      date: "2026-08-14",
      publishedAt: "2026-08-14T14:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Keep every version of a task file",
      body: "Task attachments now keep real release labels such as v2024.2.0 alongside an internal revision history. Upload an updated file from its menu, review every retained release, and download any earlier version without replacing or losing it.",
      href: "/tasks",
      tags: ["tasks", "attachments", "versions", "files"],
    },
    {
      id: "2026-08-14-ee-dictionary-connection-recovery",
      date: "2026-08-14",
      publishedAt: "2026-08-14T12:00:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "EE Data Dictionary loads more reliably",
      body: "The EE table index and table details now recover automatically from brief database connection interruptions instead of showing a full-page error.",
      href: "/ee-dictionary",
      tags: ["ee-dictionary", "reliability", "database"],
      audience: "admin",
    },
    {
      id: "2026-08-13-ee-data-dictionary",
      date: "2026-08-13",
      publishedAt: "2026-08-13T14:00:00.000Z",
      kind: "new",
      module: "admin",
      title: "New: searchable EE SQL data dictionary",
      body: "Admins can now browse the Lifelong Learning Extended Education database schema (906 tables, 9,400+ columns) from a new \"DB Dictionary\" nav item — instant search across table and column names, replacing the source Word doc that froze past a few hundred results.",
      href: "/ee-dictionary",
      tags: ["admin", "database", "search"],
      audience: "admin",
    },
    {
      id: "2026-08-13-edit-your-task-comments",
      date: "2026-08-13",
      publishedAt: "2026-08-13T12:45:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Edit your task comments",
      body: "You can now edit your own comments and thread replies without losing rich formatting, images, or mentions. Updated comments are clearly marked as edited.",
      href: "/tasks",
      tags: ["tasks", "comments", "activity", "mentions"],
    },
    {
      id: "2026-08-13-top-aligned-comment-avatars",
      date: "2026-08-13",
      publishedAt: "2026-08-13T12:30:00.000Z",
      kind: "fixed",
      module: "tasks",
      title: "Comment avatars stay with the author",
      body: "Avatars now remain at the top of task comments beside the author heading, including comments with long pasted content or images.",
      href: "/tasks",
      tags: ["tasks", "comments", "activity"],
    },
    {
      id: "2026-08-13-task-tag-connection-recovery",
      date: "2026-08-13",
      publishedAt: "2026-08-13T12:15:00.000Z",
      kind: "fixed",
      module: "tasks",
      title: "Task details recover from brief connection drops",
      body: "Opening a task now retries its tag lookup after a temporary database interruption instead of replacing the entire task page with an error.",
      href: "/tasks",
      tags: ["tasks", "reliability", "tags"],
    },
    {
      id: "2026-08-13-scrollable-long-task-comments",
      date: "2026-08-13",
      publishedAt: "2026-08-13T12:00:00.000Z",
      kind: "fixed",
      module: "tasks",
      title: "Long task comments stay manageable",
      body: "Pasted emails, API examples, and other long content now scroll inside the task comment editor, keeping the Comment button within reach.",
      href: "/tasks",
      tags: ["tasks", "comments", "editor"],
    },
    {
      id: "2026-08-12-board-card-custom-fields",
      date: "2026-08-12",
      publishedAt: "2026-08-12T13:30:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Choose the details shown on Board cards",
      body: "Each Board view can now show the custom fields that matter to its workflow. Use Card fields to select compact card details, clear them, and keep the configuration after refresh.",
      href: "/tasks",
      tags: ["tasks", "board", "custom-fields", "views"],
    },
    {
      id: "2026-08-12-default-task-type",
      date: "2026-08-12",
      publishedAt: "2026-08-12T13:15:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Every task has a clear type",
      body: "Regular work now uses Task as its built-in default type. Task Type grouping and filters show Task instead of an unclear No value group, while Project and other configured types remain available.",
      href: "/tasks",
      tags: ["tasks", "task-types", "grouping"],
    },
    {
      id: "2026-08-12-doc-body-font-sizing",
      date: "2026-08-12",
      publishedAt: "2026-08-12T13:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Document font size applies throughout the page",
      body: "Small, Default, and Large now resize the complete document body—including headings, paragraphs, lists, and tables—in both reading and editing modes.",
      href: "/docs",
      tags: ["docs", "page-styles", "typography"],
    },
    {
      id: "2026-08-12-responsive-doc-history",
      date: "2026-08-12",
      publishedAt: "2026-08-12T12:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Document history fits every screen",
      body: "Version history now uses the full available drawer width and adapts its timeline and comparison for smaller screens, without clipped text or sideways page scrolling.",
      href: "/docs",
      tags: ["docs", "version-history", "responsive", "change-control"],
    },
    {
      id: "2026-08-11-reusable-aacc-teams",
      date: "2026-08-11",
      publishedAt: "2026-08-11T15:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Work together with reusable AACC Teams",
      body: "Admins can create Teams with memorable @aliases and manage membership directly in AACC Hub. Assign a task, mention a Team in a comment, or grant a Team access to a workspace, folder, or list in one step, while Entra groups remain focused on application access.",
      href: "/admin/groups",
      tags: ["teams", "assignments", "mentions", "permissions"],
    },
    {
      id: "2026-08-11-sidebar-folder-renaming",
      date: "2026-08-11",
      publishedAt: "2026-08-11T14:45:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Rename folders from the sidebar",
      body: "Workspace owners can now right-click any folder or subfolder and rename it without moving its contents or breaking existing links.",
      href: "/tasks",
      tags: ["tasks", "folders", "navigation"],
    },
    {
      id: "2026-08-11-doc-outline-final-heading",
      date: "2026-08-11",
      publishedAt: "2026-08-11T14:30:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Document outlines reach the final section",
      body: "The last heading in a document outline is now selectable even when the page has reached its maximum scroll position. Outline navigation also lands headings consistently inside the reading area.",
      href: "/docs",
      tags: ["docs", "outline", "navigation"],
    },
    {
      id: "2026-08-11-database-reconnect-resilience",
      date: "2026-08-11",
      publishedAt: "2026-08-11T14:15:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "Task pages recover from brief database interruptions",
      body: "Task workspaces now retry their initial page data after a short database or container-network interruption, instead of immediately showing a failed-query screen during a restart.",
      href: "/tasks",
      tags: ["tasks", "database", "reliability"],
    },
    {
      id: "2026-08-11-complete-whats-new-history",
      date: "2026-08-11",
      publishedAt: "2026-08-11T14:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "The complete product history is always available",
      body: "What's New now includes New and Full history views with update counts. Switch between unread announcements and every curated AACC Hub release note without leaving the dialog.",
      href: "/",
      tags: ["whats-new", "history", "updates", "navigation"],
    },
    {
      id: "2026-08-11-compact-resizable-task-columns",
      date: "2026-08-11",
      publishedAt: "2026-08-11T13:45:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Resizable task columns use every pixel",
      body: "Task titles and text-based custom fields no longer reserve empty space for hidden controls. Copy, clear, tag, and edit actions now appear over the cell on hover, keeping resized columns compact.",
      href: "/tasks",
      tags: ["tasks", "list-view", "columns", "custom-fields"],
    },
    {
      id: "2026-08-11-task-row-reordering",
      date: "2026-08-11",
      publishedAt: "2026-08-11T13:30:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Put tasks in the order your team needs",
      body: "Drag the handle beside a task to place it before or after another task. Grouped views support reordering within each group, and the custom order is saved for everyone viewing the list.",
      href: "/tasks",
      tags: ["tasks", "list-view", "drag-and-drop", "ordering"],
    },
    {
      id: "2026-08-11-task-groups-alphabetical",
      date: "2026-08-11",
      publishedAt: "2026-08-11T13:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Task groups are consistently alphabetical",
      body: "Every Group by view now orders its displayed group names A–Z, including statuses, priorities, task types, people, and custom-field options. Empty values remain together at the end.",
      href: "/tasks",
      tags: ["tasks", "grouping", "sorting", "list-view"],
    },
    {
      id: "2026-08-11-super-agent-greeting-context-fix",
      date: "2026-08-11",
      publishedAt: "2026-08-11T12:30:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "Super Agents stay focused on the current message",
      body: "Greetings, acknowledgements, and short conversation-closing replies no longer invoke document search or a paid model call. Linked document screenshots are only sent to an agent for visual questions, preventing unrelated knowledge from taking over the conversation.",
      href: "/chat",
      tags: ["chat", "super-agents", "knowledge", "reliability"],
    },
    {
      id: "2026-08-11-aacc-hub-brand-cleanup",
      date: "2026-08-11",
      publishedAt: "2026-08-11T12:00:00.000Z",
      kind: "improved",
      module: "platform",
      title: "AACC Hub language is consistent across the platform",
      body: "Forms, Super Agents, Docs, directory settings, and help text now use AACC Hub language consistently, with obsolete migration utilities and legacy product comparisons removed.",
      href: "/",
      tags: ["brand", "platform", "aacc-hub"],
    },
    {
      id: "2026-08-10-delete-custom-fields",
      date: "2026-08-10",
      publishedAt: "2026-08-10T16:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Deleted custom fields are recoverable",
      body: "Deleting an active or archived custom field now moves it to Settings → Trash with its task values intact. Restore it within 30 days, or use Delete forever to purge the field and its values.",
      href: "/tasks",
      tags: ["tasks", "custom-fields", "settings"],
    },
    {
      id: "2026-08-10-compact-custom-field-pickers",
      date: "2026-08-10",
      publishedAt: "2026-08-10T15:30:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Custom-field menus use less space",
      body: "Dropdown and color-field menus are now denser and easier to scan, with compact rows, markers, and spacing.",
      href: "/tasks",
      tags: ["tasks", "custom-fields", "dropdowns"],
    },
    {
      id: "2026-08-10-task-title-status-rings",
      date: "2026-08-10",
      publishedAt: "2026-08-10T15:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Task status is visible beside every title",
      body: "A clickable progress-style status circle now appears before each task title: empty for not started, half-filled for active work, and checked when done. Select the circle to change status without leaving the list.",
      href: "/tasks",
      tags: ["tasks", "status", "list-view"],
    },
    {
      id: "2026-08-10-sidebar-list-reordering",
      date: "2026-08-10",
      publishedAt: "2026-08-10T14:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Reorder lists from the sidebar",
      body: "Drag a list above or below another list and the sidebar updates immediately, keeping workspace navigation in the order your team uses it.",
      href: "/tasks",
      tags: ["navigation", "lists", "drag-and-drop"],
    },
    {
      id: "2026-08-10-custom-field-quick-actions",
      date: "2026-08-10",
      publishedAt: "2026-08-10T13:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Copy or clear text custom fields quickly",
      body: "Hover over a text or number custom field to copy its value or clear it without opening the editor, using compact AACC Hub task-table actions.",
      href: "/tasks",
      tags: ["tasks", "custom-fields", "quick-actions"],
    },
    {
      id: "2026-08-10-sidebar-workspace-hierarchy",
      date: "2026-08-10",
      publishedAt: "2026-08-10T12:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Workspace children are easier to scan",
      body: "Folders and lists now sit farther under their workspace with a subtle AACC teal guide, making the sidebar hierarchy clearer at a glance.",
      href: "/tasks",
      tags: ["navigation", "workspaces", "sidebar", "ux"],
    },
    {
      id: "2026-08-09-tasks-task-types",
      date: "2026-08-09",
      publishedAt: "2026-08-09T20:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Task Types, checklists, and a Project delivery timeline",
      body: "Configure custom task types (with icons) per Space from Space settings → Task Types. Tasks now support checklists too, and any type with \"Delivery timeline\" turned on (e.g. Project) shows a completion bar on the task detail view, driven by subtask and checklist progress. Task Type is also available as a List view filter and \"Group by\" option once a space has at least one type.",
      href: "/tasks",
      tags: ["tasks", "task-types", "checklists", "projects"],
    },
    {
      id: "2026-08-09-tasks-table-view",
      date: "2026-08-09",
      publishedAt: "2026-08-09T19:00:00.000Z",
      kind: "new",
      module: "tasks",
      title: "New spreadsheet-style Table view",
      body: "Add a Table view from a list's \"+ View\" menu for an Excel-like grid: click-drag or Shift-click to select a range of cells, copy/paste across cells (including into a larger selection), and drag the fill handle to copy a value down a column.",
      href: "/tasks",
      tags: ["tasks", "table", "spreadsheet", "views"],
    },
    {
      id: "2026-08-09-admin-ai-usage",
      date: "2026-08-09",
      publishedAt: "2026-08-09T18:00:00.000Z",
      kind: "new",
      module: "admin",
      title: "New Admin tab: AI Usage",
      body: "Settings → AI Usage now shows every AI call platform-wide — who triggered it, which Super Agent, model, purpose, duration, and prompt/completion/total tokens — with breakdowns by agent, user, model, and purpose.",
      href: "/?settings=ai",
      tags: ["admin", "ai", "tokens", "observability"],
      audience: "admin",
    },
    {
      id: "2026-08-09-chat-image-vision",
      date: "2026-08-09",
      publishedAt: "2026-08-09T17:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Paste images into Super Agent chat",
      body: "Drop or paste a screenshot into a chat with a Super Agent and it can now actually look at it — not just see that an image was sent.",
      href: "/chat",
      tags: ["chat", "super-agents", "vision"],
    },
    {
      id: "2026-08-09-docs-read-first-editing",
      date: "2026-08-09",
      publishedAt: "2026-08-09T16:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Docs open in read mode",
      body: "Documents now open for reading without creating a save. Double-click the page to enter editing; saving begins only after you make a change.",
      href: "/docs",
      tags: ["docs", "editing", "reliability"],
    },
    {
      id: "2026-08-09-docs-revision-diff",
      date: "2026-08-09",
      publishedAt: "2026-08-09T15:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Review Doc revisions as clear changes",
      body: "Version history now shows a focused red/green change review, including image additions and removals, instead of a plain-text comparison.",
      href: "/docs",
      tags: ["docs", "version-history", "change-control"],
    },
    {
      id: "2026-08-09-docs-version-history",
      date: "2026-08-09",
      publishedAt: "2026-08-09T14:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Docs now keep a version history",
      body: "Open History on a Doc to view every saved version, see who made it, compare its text with the current page, and restore a prior version. Restores are recorded too for a complete change trail.",
      href: "/docs",
      tags: ["docs", "version-history", "audit", "cewd"],
    },
    {
      id: "2026-08-09-super-agent-doc-citations",
      date: "2026-08-09",
      publishedAt: "2026-08-09T12:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Super Agent document citations read naturally",
      body: "Chat replies now format linked Doc references as clear citations instead of leaving stray punctuation that can look like an emoticon.",
      href: "/chat",
      tags: ["chat", "super-agents", "docs"],
    },
    {
      id: "2026-08-08-doc-image-save-batching",
      date: "2026-08-08",
      publishedAt: "2026-08-08T22:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Large Word pastes save images reliably",
      body: "Docs now preserve permanent image URLs through collaboration and save a multi-image paste as one completed batch instead of repeatedly storing intermediate placeholders. Repeated copies of the same Word image also reuse one stored attachment.",
      href: "/docs",
      tags: ["docs", "images", "paste", "collaboration", "reliability"],
    },
    {
      id: "2026-08-08-doc-outline-fixed-rail",
      date: "2026-08-08",
      publishedAt: "2026-08-08T21:45:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Page outline floats with you while scrolling",
      body: "The rounded Doc page outline now stays floating beside the page as you read or jump between headings. Its highlighted entry also follows the current section within longer outlines.",
      href: "/docs",
      tags: ["docs", "outline", "navigation"],
    },
    {
      id: "2026-08-08-doc-outline-heading-freeze",
      date: "2026-08-08",
      publishedAt: "2026-08-08T21:30:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Heading changes stay responsive with Page outline",
      body: "Changing selected Doc text into a heading no longer causes the editor to lock up when Page outline is enabled.",
      href: "/docs",
      tags: ["docs", "outline", "editor", "reliability"],
    },
    {
      id: "2026-08-08-shell-database-recovery",
      date: "2026-08-08",
      publishedAt: "2026-08-08T21:15:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Workspace navigation recovers from brief database interruptions",
      body: "AACC Hub now retries temporary database connection failures while loading workspace navigation and avoids opening a burst of role checks at the same time.",
      tags: ["navigation", "reliability", "database"],
    },
    {
      id: "2026-08-08-doc-page-outline-navigation",
      date: "2026-08-08",
      publishedAt: "2026-08-08T21:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Page outline now navigates your Doc",
      body: "The Page outline style now builds a live list from the headings in your Doc. It follows the section you are reading and jumps directly to a heading when selected.",
      href: "/docs",
      tags: ["docs", "outline", "navigation"],
    },
    {
      id: "2026-08-08-word-paste-images-persist",
      date: "2026-08-08",
      publishedAt: "2026-08-08T12:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Word images stay in Docs after pasting",
      body: "Pasting from Word now places text immediately, shows steady image placeholders with upload progress, and saves each permanent image as soon as it is ready. Images no longer flicker, disappear when uploads finish, or get lost when collaboration connects.",
      href: "/docs",
      tags: ["docs", "images", "paste", "reliability"],
    },
    {
      id: "2026-08-08-super-agent-memory-search-ui",
      date: "2026-08-08",
      publishedAt: "2026-08-08T20:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Search past Super Agent chats & manage memory",
      body: "Agents can pull short snippets from earlier conversations when you ask what you discussed before. On Edit Agent → Memory, add, edit, or delete preferences, facts, and when→do flows.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory"],
    },
    {
      id: "2026-08-08-super-agent-memory-layers",
      date: "2026-08-08",
      publishedAt: "2026-08-08T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Smarter Super Agent memory (less chat bloat)",
      body: "Agents keep small curated preferences, facts, and when→do flows on the prompt — not full chat logs. Longer threads use a rolling summary plus the last few messages to save tokens.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory"],
    },
    {
      id: "2026-08-08-super-agent-disable-delete",
      date: "2026-08-08",
      publishedAt: "2026-08-08T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Turn Super Agents off or delete them",
      body: "From Super Agents hub or agent settings, turn an agent off so it leaves Chat, or permanently delete ones you own (Super Admins can remove system agents too).",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-ops-guide",
      date: "2026-08-07",
      publishedAt: "2026-08-08T00:10:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Smarter Super Agents — Docs formatting & safety",
      body: "Agents now know how the Hub works, write Docs with proper headings and lists (Markdown → TipTap), refuse accidental page wipes, and can tell you what they can vs can’t do from chat.",
      href: "/chat",
      tags: ["chat", "super-agents", "docs", "safety"],
    },
    {
      id: "2026-08-07-super-agent-create-groups",
      date: "2026-08-07",
      publishedAt: "2026-08-07T23:55:00.000Z",
      kind: "new",
      module: "shell",
      title: "Control who can create Super Agents",
      body: "Super Admins can open Settings → Super Agents and allow selected Entra groups to create agents. Super Admins can always create; everyone else follows this toggle.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "settings", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-people",
      date: "2026-08-07",
      publishedAt: "2026-08-07T23:30:00.000Z",
      kind: "new",
      module: "shell",
      title: "Share Super Agents with admins and users",
      body: "Add people to a Super Agent as Members (chat) or Admins (edit). Optionally limit chat access to the agent roster.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "sharing", "permissions"],
    },
    {
      id: "2026-08-07-super-agent-owner-writes",
      date: "2026-08-07",
      publishedAt: "2026-08-07T22:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Owners can update docs and memory in Super Agent chat",
      body: "If you created a Super Agent (or you're a Super Admin), you can ask it to append knowledge to linked Docs and to remember preferences — right from the conversation.",
      href: "/chat",
      tags: ["chat", "super-agents", "docs", "memory"],
    },
    {
      id: "2026-08-07-super-agent-memory-ui",
      date: "2026-08-07",
      publishedAt: "2026-08-07T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Super Agents remember context and support editing",
      body: "Agent setup now uses Instructions, Triggers, Skills, Knowledge, and Memory tabs. Tagged Docs become knowledge automatically, and agents can keep recent context, preferences, and learned facts so they improve over time.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "memory", "knowledge"],
    },
    {
      id: "2026-08-07-super-agent-builder",
      date: "2026-08-07",
      publishedAt: "2026-08-07T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Build your own Super Agents",
      body: "Admins can create Super Agents from a natural-language brief, edit instructions, tools, Docs knowledge, and models, then chat with them inside AACC Hub. Use a stronger model to draft the agent and a cheaper one for everyday replies.",
      href: "/chat/agents",
      tags: ["chat", "super-agents", "builder", "docs"],
    },
    {
      id: "2026-08-06-chat-super-agents",
      date: "2026-08-06",
      publishedAt: "2026-08-06T22:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Chat with Super Agents",
      body: "Open Chat from the sidebar and talk to Super Agents like Deadline Dale in private threads that can surface overdue tasks as clickable chips.",
      href: "/chat",
      tags: ["chat", "super-agents", "ai"],
    },
    {
      id: "2026-08-06-assignee-label-left",
      date: "2026-08-06",
      publishedAt: "2026-08-06T16:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "People and tags are easier to scan",
      body: "The Assignees and Tags labels now sit to the left of their pickers in task creation and task details, making task fields more compact and consistent.",
      href: "/tasks",
      tags: ["tasks", "assignees", "tags", "layout"],
    },
    {
      id: "2026-08-06-custom-field-label-layouts",
      date: "2026-08-06",
      publishedAt: "2026-08-06T15:30:00.000Z",
      kind: "new",
      module: "tasks",
      title: "Custom fields explain themselves",
      body: "Custom fields can now include optional help text and place their label above, below, beside, inside, or out of sight. The chosen presentation follows the field into task creation and task details.",
      href: "/tasks",
      tags: ["custom-fields", "task-layout", "accessibility"],
    },
    {
      id: "2026-08-06-super-admin-hidden-permissions",
      date: "2026-08-06",
      publishedAt: "2026-08-06T15:00:00.000Z",
      kind: "fixed",
      module: "admin",
      title: "One clear Admin role in permissions",
      body: "The permissions matrix now shows only the configurable space Admin role. Super Admin remains an unrestricted platform safeguard managed outside the matrix and cannot be accidentally edited or duplicated.",
      tags: ["permissions", "roles", "admin"],
    },
    {
      id: "2026-08-06-aacc-actions-menu-system",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Action menus now share one AACC design",
      body: "Settings, option menus, and right-click actions across AACC Hub now use consistent spacing, typography, teal focus states, branded borders, and clearer destructive actions.",
      tags: ["design", "navigation", "accessibility"],
    },
    {
      id: "2026-08-06-aacc-task-actions-menu",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Task actions get a modern AACC design",
      body: "Task option menus now use a clearer branded header, fast icon actions, organized sections, and distinct lifecycle controls. The same design appears from task tables, boards, detail pages, and right-click menus.",
      href: "/tasks",
      tags: ["tasks", "design", "navigation"],
    },
    {
      id: "2026-08-06-doc-panels-collapsed",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "A cleaner, faster Pages rail",
      body: "The Pages and Styles panels now start collapsed, while the Pages rail remains available from the first page. Hover over any page to add a subpage, duplicate its full page tree, or copy and move it between Docs from the options menu.",
      href: "/docs",
      tags: ["docs", "navigation", "editor"],
    },
    {
      id: "2026-08-06-theme-bootstrap-react-19",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Theme loading is clean in modern browsers",
      body: "The light and dark theme bootstrap no longer produces a React script warning during client rendering while still preventing a flash of the wrong theme.",
      tags: ["theme", "reliability"],
    },
    {
      id: "2026-08-06-new-doc-first-save",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:30:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "New Docs save cleanly the first time",
      body: "Creating and immediately editing a Doc no longer produces a false message that somebody else saved the page. Local autosave and live collaboration now choose one save path before editing begins.",
      href: "/docs",
      tags: ["docs", "autosave", "collaboration"],
    },
    {
      id: "2026-08-06-local-login-visibility",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:00:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "Local account sign-in is available when enabled",
      body: "The login page now shows the AACC email and password form in production environments that explicitly allow local accounts. If no sign-in method is configured, the page explains what needs administrator attention instead of appearing empty.",
      href: "/login",
      tags: ["login", "reliability"],
    },
    {
      id: "2026-08-05-platform-connection-stability",
      date: "2026-08-05",
      publishedAt: "2026-08-06T03:30:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "More reliable connections across AACC Hub",
      body: "Docs collaboration, presence updates, and database-backed screens now recover more gracefully from brief connection interruptions. Health checks also report transient database failures more reliably.",
      tags: ["reliability", "docs", "platform"],
    },
    {
      id: "2026-08-05-cewd-operations-workspace",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:55:00.000Z",
      kind: "new",
      module: "tasks",
      title: "CEWD Operations replaces the legacy demo workspace",
      body: "The old Safety sample has become a CEWD-focused workspace for discovering, validating, and delivering cross-functional workflows. It starts with a guided pilot-selection task and CEWD-specific fields.",
      href: "/tasks/cewd-operations",
      tags: ["cewd", "workflows"],
    },
    {
      id: "2026-08-05-duplicate-docs-navigation",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:45:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "One clear home for Docs",
      body: "The duplicate Docs item has been removed from navigation. The remaining Docs destination opens the shared knowledge hub.",
      href: "/docs",
      tags: ["navigation", "docs"],
    },
    {
      id: "2026-08-05-aacc-operations-hub-brand",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "AACC Hub gets its college look",
      body: "The platform now uses AACC's logo and visual identity, with college teal, deep teal, and orange carried through navigation, forms, dashboards, notifications, and dark mode.",
      href: "/",
      tags: ["brand", "platform"],
    },
    {
      id: "2026-08-05-docs-all-docs-hub",
      date: "2026-08-05",
      publishedAt: "2026-08-05T22:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "All Docs hub keeps navigation focused",
      body: "Docs now opens a table of every root doc (name, location, updated, sharing). Nested pages and multi-level subpages live inside the open document outline — not under the main nav. Templates for Project Overview, Meeting Notes, and Wiki are on the hub.",
      href: "/docs",
      tags: ["docs", "hub", "wiki"],
    },
    {
      id: "2026-08-05-docs-tree-embeds",
      date: "2026-08-05",
      publishedAt: "2026-08-05T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Live task embeds in Docs",
      body: "In any page, type / and choose Task to embed a live chip with number, title, and status that opens the task.",
      href: "/docs",
      tags: ["docs", "embeds"],
    },
    {
      id: "2026-08-05-docs-module",
      date: "2026-08-05",
      publishedAt: "2026-08-05T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Docs — knowledge pages next to your work",
      body: "Create SOPs, meeting notes, and wikis from the Docs hub or directly on a task. Pages live in a space, nest as subpages, support protect + verify for freshness, and link back to tasks so knowledge stays with the work.",
      href: "/docs",
      tags: ["docs", "wiki", "knowledge"],
    },
    {
      id: "2026-08-04-whats-new-header",
      date: "2026-08-04",
      publishedAt: "2026-08-04T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: '"What\'s New" updates in the header',
      body: "A megaphone icon in the top bar now shows what changed after each update, so you always know what's new since your last visit.",
      tags: ["changelog", "onboarding"],
    },
  ],
};
