/**
 * Proprietary — Copyright (c) 2024–2026 Kim Gurinov (Gurver).
 * Author: Kim Gurinov <kurinov@gurver.org> <kim@gurver.com>
 * Website: https://gurver.com
 * Fingerprint: GURVER-KG-AITIM-2026-7F3C9E2A
 * License: Proprietary. All rights reserved. See LICENSE / COPYRIGHT.
 *
 * Curated product changelog. Newest entries first is optional — the feed
 * helpers sort by publishedAt. Prefer appending new objects at the top for
 * human readability when editing.
 *
 * When you ship a user-visible change (any AI or human), add an entry here.
 * See docs/whats-new.md.
 */

import type { WhatsNewFeed } from "./types";

export const whatsNewFeed: WhatsNewFeed = {
  schemaVersion: 1,
  entries: [
    {
      id: "2026-08-06-super-admin-hidden-permissions",
      date: "2026-08-06",
      publishedAt: "2026-08-06T15:00:00.000Z",
      kind: "fixed",
      module: "admin",
      title: "One clear Admin role in permissions",
      body: "The permissions matrix now shows only the configurable space Admin role. Super Admin remains an unrestricted platform safeguard managed outside the matrix and cannot be accidentally edited or duplicated.",
      tags: ["permissions", "roles", "admin"],
    },
    {
      id: "2026-08-06-aacc-actions-menu-system",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Action menus now share one AACC design",
      body: "Settings, option menus, and right-click actions across the Operations Hub now use consistent spacing, typography, teal focus states, branded borders, and clearer destructive actions.",
      tags: ["design", "navigation", "accessibility"],
    },
    {
      id: "2026-08-06-aacc-task-actions-menu",
      date: "2026-08-06",
      publishedAt: "2026-08-06T14:00:00.000Z",
      kind: "improved",
      module: "tasks",
      title: "Task actions get a modern AACC design",
      body: "Task option menus now use a clearer branded header, fast icon actions, organized sections, and distinct lifecycle controls. The same design appears from task tables, boards, detail pages, and right-click menus.",
      href: "/tasks",
      tags: ["tasks", "design", "navigation"],
    },
    {
      id: "2026-08-06-doc-panels-collapsed",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "A cleaner, faster Pages rail",
      body: "The Pages and Styles panels now start collapsed, while the Pages rail remains available from the first page. Hover over any page to add a subpage, duplicate its full page tree, or copy and move it between Docs from the options menu.",
      href: "/docs",
      tags: ["docs", "navigation", "editor"],
    },
    {
      id: "2026-08-06-theme-bootstrap-react-19",
      date: "2026-08-06",
      publishedAt: "2026-08-06T13:00:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "Theme loading is clean in modern browsers",
      body: "The light and dark theme bootstrap no longer produces a React script warning during client rendering while still preventing a flash of the wrong theme.",
      tags: ["theme", "reliability"],
    },
    {
      id: "2026-08-06-new-doc-first-save",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:30:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "New Docs save cleanly the first time",
      body: "Creating and immediately editing a Doc no longer produces a false message that somebody else saved the page. Local autosave and live collaboration now choose one save path before editing begins.",
      href: "/docs",
      tags: ["docs", "autosave", "collaboration"],
    },
    {
      id: "2026-08-06-local-login-visibility",
      date: "2026-08-06",
      publishedAt: "2026-08-06T12:00:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "Local account sign-in is available when enabled",
      body: "The login page now shows the AACC email and password form in production environments that explicitly allow local accounts. If no sign-in method is configured, the page explains what needs administrator attention instead of appearing empty.",
      href: "/login",
      tags: ["login", "reliability"],
    },
    {
      id: "2026-08-05-platform-connection-stability",
      date: "2026-08-05",
      publishedAt: "2026-08-06T03:30:00.000Z",
      kind: "fixed",
      module: "platform",
      title: "More reliable connections across the Operations Hub",
      body: "Docs collaboration, presence updates, and database-backed screens now recover more gracefully from brief connection interruptions. Health checks also report transient database failures more reliably.",
      tags: ["reliability", "docs", "platform"],
    },
    {
      id: "2026-08-05-cewd-operations-workspace",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:55:00.000Z",
      kind: "new",
      module: "tasks",
      title: "CEWD Operations replaces the legacy demo workspace",
      body: "The old Safety sample has become a CEWD-focused workspace for discovering, validating, and delivering cross-functional workflows. It starts with a guided pilot-selection task and CEWD-specific fields.",
      href: "/tasks/cewd-operations",
      tags: ["cewd", "workflows"],
    },
    {
      id: "2026-08-05-duplicate-docs-navigation",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:45:00.000Z",
      kind: "fixed",
      module: "shell",
      title: "One clear home for Docs",
      body: "The duplicate Docs item has been removed from navigation. The remaining Docs destination opens the shared knowledge hub.",
      href: "/docs",
      tags: ["navigation", "docs"],
    },
    {
      id: "2026-08-05-aacc-operations-hub-brand",
      date: "2026-08-05",
      publishedAt: "2026-08-05T23:30:00.000Z",
      kind: "improved",
      module: "shell",
      title: "AACC Operations Hub gets its college look",
      body: "The platform now uses AACC's logo and visual identity, with college teal, deep teal, and orange carried through navigation, forms, dashboards, notifications, and dark mode.",
      href: "/",
      tags: ["brand", "platform"],
    },
    {
      id: "2026-08-05-docs-all-docs-hub",
      date: "2026-08-05",
      publishedAt: "2026-08-05T22:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "All Docs hub — like ClickUp, without the sidebar tree",
      body: "Docs now opens a table of every root doc (name, location, updated, sharing). Nested pages and multi-level subpages live inside the open document outline — not under the main nav. Templates for Project Overview, Meeting Notes, and Wiki are on the hub.",
      href: "/docs",
      tags: ["docs", "hub", "wiki"],
    },
    {
      id: "2026-08-05-docs-tree-embeds",
      date: "2026-08-05",
      publishedAt: "2026-08-05T18:00:00.000Z",
      kind: "improved",
      module: "shell",
      title: "Live task embeds in Docs",
      body: "In any page, type / and choose Task to embed a live chip with number, title, and status that opens the task.",
      href: "/docs",
      tags: ["docs", "embeds"],
    },
    {
      id: "2026-08-05-docs-module",
      date: "2026-08-05",
      publishedAt: "2026-08-05T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: "Docs — knowledge pages next to your work",
      body: "Create SOPs, meeting notes, and wikis from the Docs hub or directly on a task. Pages live in a space, nest as subpages, support protect + verify for freshness, and link back to tasks so knowledge stays with the work.",
      href: "/docs",
      tags: ["docs", "wiki", "knowledge"],
    },
    {
      id: "2026-08-04-whats-new-header",
      date: "2026-08-04",
      publishedAt: "2026-08-04T12:00:00.000Z",
      kind: "new",
      module: "shell",
      title: '"What\'s New" updates in the header',
      body: "A megaphone icon in the top bar now shows what changed after each update, so you always know what's new since your last visit.",
      tags: ["changelog", "onboarding"],
    },
  ],
};
